# Generated by Django 6.0.3 on 2026-03-17 23:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("rich_text", 1),
                    ("card", 3),
                    ("hero", 9),
                    ("cta_callout", 13),
                    ("code", 16),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.blocks.TextBlock", (), {}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("body", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"max_length": 200}),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 400, "required": False},
                    ),
                    6: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Button text", "max_length": 100, "required": False},
                    ),
                    8: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Button URL", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 4),
                                ("subheading", 5),
                                ("body", 6),
                                ("cta_text", 7),
                                ("cta_url", 8),
                            ]
                        ],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Button text", "max_length": 100},
                    ),
                    11: ("wagtail.blocks.URLBlock", (), {"label": "Button URL"}),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("accent", "Accent"),
                            ],
                            "help_text": "Controls the visual style of the callout panel.",
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 4),
                                ("text", 2),
                                ("button_text", 10),
                                ("button_url", 11),
                                ("style", 12),
                            ]
                        ],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bash", "Bash/Shell"),
                                ("css", "CSS"),
                                ("diff", "diff"),
                                ("html", "HTML"),
                                ("javascript", "Javascript"),
                                ("json", "JSON"),
                                ("python", "Python"),
                                ("scss", "SCSS"),
                                ("yaml", "YAML"),
                            ],
                            "help_text": "Coding language",
                            "identifier": "language",
                            "label": "Language",
                        },
                    ),
                    15: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"identifier": "code", "label": "Code"},
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("language", 14), ("code", 15)]],
                        {"label": "Code"},
                    ),
                },
            ),
        ),
    ]
