# Generated by Django 6.0.3 on 2026-03-17 23:53

from django.contrib.auth import get_user_model
from django.db import migrations

User = get_user_model()


def setup_test_content(apps, schema_editor):
    User.objects.create_superuser(
        username="admin",
        email="admin@example.com",
        password="admin",
    )


def reverse_setup_test_content(apps, schema_editor):
    User.objects.filter(username="admin").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0003_alter_testpage_body"),
    ]

    operations = [
        migrations.RunPython(setup_test_content, reverse_setup_test_content),
    ]
