# Generated by Django 6.0.3 on 2026-03-18 00:18

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0004_auto_20260317_2353"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("rich_text", 1),
                    ("card", 3),
                    ("hero", 10),
                    ("cta_callout", 13),
                    ("header", 16),
                    ("bullet_list", 18),
                    ("code", 21),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.blocks.TextBlock", (), {}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("body", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"max_length": 200}),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 400, "required": False},
                    ),
                    6: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Button text", "max_length": 100},
                    ),
                    8: ("wagtail.blocks.URLBlock", (), {"label": "Button URL"}),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 7), ("url", 8)]],
                        {"label": "Call to action", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 4), ("subheading", 5), ("body", 6), ("cta", 9)]],
                        {},
                    ),
                    11: ("wagtail.blocks.StructBlock", [[("text", 7), ("url", 8)]], {}),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("accent", "Accent"),
                            ],
                            "help_text": "Controls the visual style of the callout panel.",
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 4), ("text", 2), ("button", 11), ("style", 12)]],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h1", "H1"),
                                ("h2", "H2"),
                                ("h3", "H3"),
                                ("h4", "H4"),
                                ("h5", "H5"),
                                ("h6", "H6"),
                            ],
                            "label": "Header Size",
                        },
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Text", "max_length": 50},
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("header", 14), ("text", 15)]],
                        {},
                    ),
                    17: ("wagtail.blocks.ListBlock", (0,), {"label": "Items"}),
                    18: ("wagtail.blocks.StructBlock", [[("content", 17)]], {}),
                    19: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bash", "Bash/Shell"),
                                ("css", "CSS"),
                                ("diff", "diff"),
                                ("html", "HTML"),
                                ("javascript", "Javascript"),
                                ("json", "JSON"),
                                ("python", "Python"),
                                ("scss", "SCSS"),
                                ("yaml", "YAML"),
                            ],
                            "help_text": "Coding language",
                            "identifier": "language",
                            "label": "Language",
                        },
                    ),
                    20: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"identifier": "code", "label": "Code"},
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("language", 19), ("code", 20)]],
                        {"label": "Code"},
                    ),
                },
            ),
        ),
    ]
