# Generated by Django 5.1.15 on 2026-03-19 20:04

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0005_refactor_button_block"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("rich_text", 1),
                    ("card", 3),
                    ("hero", 12),
                    ("cta_callout", 15),
                    ("badge", 18),
                    ("cms_button", 22),
                    ("enhanced_hero", 30),
                    ("feature_grid", 37),
                    ("pricing_section", 44),
                    ("stats_section", 49),
                    ("testimonial_section", 52),
                    ("text_with_image", 57),
                    ("logo_cloud", 62),
                    ("cta_banner", 65),
                    ("faq_section", 68),
                    ("footer_section", 74),
                    ("rich_text_section", 76),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.blocks.TextBlock", (), {}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("body", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"max_length": 200}),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 400, "required": False},
                    ),
                    6: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Button text", "max_length": 100},
                    ),
                    8: ("wagtail.blocks.URLBlock", (), {"label": "Button URL"}),
                    9: ("wagtail.blocks.StructBlock", [[("text", 7), ("url", 8)]], {}),
                    10: (
                        "wagtail.blocks.ListBlock",
                        (9,),
                        {
                            "help_text": "Add one or more call-to-action buttons",
                            "label": "Buttons",
                            "max_num": 3,
                            "min_num": 0,
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("buttons", 10)]],
                        {"label": "Call to action", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 4), ("subheading", 5), ("body", 6), ("cta", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("buttons", 10)]],
                        {"label": "Action buttons"},
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("accent", "Accent"),
                            ],
                            "help_text": "Controls the visual style of the callout panel.",
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 4), ("text", 2), ("buttons", 13), ("style", 14)]],
                        {},
                    ),
                    16: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    17: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default"),
                                ("highlight", "Highlight"),
                                ("muted", "Muted"),
                            ]
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 16), ("variant", 17)]],
                        {},
                    ),
                    19: ("wagtail.blocks.URLBlock", (), {}),
                    20: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("outline", "Outline"),
                                ("ghost", "Ghost"),
                            ]
                        },
                    ),
                    21: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Small"),
                                ("md", "Medium"),
                                ("lg", "Large"),
                            ]
                        },
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 16), ("href", 19), ("variant", 20), ("size", 21)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 50, "required": False},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 16), ("href", 19), ("variant", 20), ("size", 21)]],
                        {"label": "Primary CTA", "required": False},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 16), ("href", 19), ("variant", 20), ("size", 21)]],
                        {"label": "Secondary CTA", "required": False},
                    ),
                    26: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": False},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 26), ("alt", 27)]],
                        {"label": "Hero Image", "required": False},
                    ),
                    29: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("left", "Left"), ("center", "Center")]},
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 23),
                                ("headline", 4),
                                ("description", 2),
                                ("primary_cta", 24),
                                ("secondary_cta", 25),
                                ("image", 28),
                                ("alignment", 29),
                            ]
                        ],
                        {},
                    ),
                    31: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    32: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("2", "2 columns"),
                                ("3", "3 columns"),
                                ("4", "4 columns"),
                            ]
                        },
                    ),
                    33: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Emoji or icon character (e.g., 🚀, ⚡, 💡)",
                            "max_length": 10,
                        },
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 33), ("title", 16), ("description", 2)]],
                        {},
                    ),
                    35: (
                        "wagtail.blocks.ListBlock",
                        (34,),
                        {"max_num": 12, "min_num": 1},
                    ),
                    36: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default"),
                                ("surface", "Surface"),
                                ("secondary", "Secondary"),
                            ]
                        },
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 23),
                                ("headline", 4),
                                ("description", 31),
                                ("columns", 32),
                                ("features", 35),
                                ("background", 36),
                            ]
                        ],
                        {},
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "e.g., $29/mo", "max_length": 50},
                    ),
                    39: ("wagtail.blocks.ListBlock", (4,), {"label": "Features"}),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 16), ("href", 19), ("variant", 20), ("size", 21)]],
                        {"label": "Call to Action"},
                    ),
                    41: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Highlight this plan with special styling",
                            "required": False,
                        },
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 16),
                                ("price", 38),
                                ("description", 2),
                                ("features", 39),
                                ("cta", 40),
                                ("highlighted", 41),
                            ]
                        ],
                        {},
                    ),
                    43: (
                        "wagtail.blocks.ListBlock",
                        (42,),
                        {"max_num": 4, "min_num": 1},
                    ),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 23),
                                ("headline", 4),
                                ("description", 31),
                                ("plans", 43),
                                ("background", 36),
                            ]
                        ],
                        {},
                    ),
                    45: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 200, "required": False},
                    ),
                    46: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "e.g., 99.9%, 10k+, $1M", "max_length": 50},
                    ),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [[("value", 46), ("label", 16)]],
                        {},
                    ),
                    48: (
                        "wagtail.blocks.ListBlock",
                        (47,),
                        {"max_num": 8, "min_num": 1},
                    ),
                    49: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 23),
                                ("headline", 45),
                                ("stats", 48),
                                ("background", 36),
                            ]
                        ],
                        {},
                    ),
                    50: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 2), ("author", 16), ("role", 16), ("avatar", 26)]],
                        {},
                    ),
                    51: (
                        "wagtail.blocks.ListBlock",
                        (50,),
                        {"max_num": 6, "min_num": 1},
                    ),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 23),
                                ("headline", 4),
                                ("testimonials", 51),
                                ("background", 36),
                            ]
                        ],
                        {},
                    ),
                    53: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 53), ("alt", 27)]],
                        {"label": "Image"},
                    ),
                    55: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("right", "Right")],
                            "label": "Image position",
                        },
                    ),
                    56: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 16), ("href", 19), ("variant", 20), ("size", 21)]],
                        {"label": "Call to Action", "required": False},
                    ),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 23),
                                ("headline", 4),
                                ("description", 2),
                                ("image", 54),
                                ("image_position", 55),
                                ("cta", 56),
                                ("background", 36),
                            ]
                        ],
                        {},
                    ),
                    58: ("wagtail.blocks.CharBlock", (), {"max_length": 255}),
                    59: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Link URL", "required": False},
                    ),
                    60: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 53), ("alt", 58), ("href", 59)]],
                        {},
                    ),
                    61: (
                        "wagtail.blocks.ListBlock",
                        (60,),
                        {"max_num": 12, "min_num": 1},
                    ),
                    62: (
                        "wagtail.blocks.StructBlock",
                        [[("headline", 45), ("logos", 61), ("background", 36)]],
                        {},
                    ),
                    63: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 16), ("href", 19), ("variant", 20), ("size", 21)]],
                        {"label": "Primary CTA"},
                    ),
                    64: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("default", "Default"), ("primary", "Primary")]},
                    ),
                    65: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("headline", 4),
                                ("description", 31),
                                ("primary_cta", 63),
                                ("secondary_cta", 25),
                                ("variant", 64),
                            ]
                        ],
                        {},
                    ),
                    66: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 4), ("answer", 2)]],
                        {},
                    ),
                    67: (
                        "wagtail.blocks.ListBlock",
                        (66,),
                        {"max_num": 20, "min_num": 1},
                    ),
                    68: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 23),
                                ("headline", 4),
                                ("description", 31),
                                ("faqs", 67),
                                ("background", 36),
                            ]
                        ],
                        {},
                    ),
                    69: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Brand name or tagline", "max_length": 100},
                    ),
                    70: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 16), ("url", 19)]],
                        {},
                    ),
                    71: ("wagtail.blocks.ListBlock", (70,), {}),
                    72: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 16), ("links", 71)]],
                        {},
                    ),
                    73: ("wagtail.blocks.ListBlock", (72,), {"max_num": 4}),
                    74: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("brand_text", 69),
                                ("description", 31),
                                ("columns", 73),
                                ("copyright", 4),
                            ]
                        ],
                        {},
                    ),
                    75: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Small (640px)"),
                                ("md", "Medium (768px)"),
                                ("lg", "Large (1024px)"),
                            ]
                        },
                    ),
                    76: (
                        "wagtail.blocks.StructBlock",
                        [[("content", 1), ("max_width", 75), ("background", 36)]],
                        {},
                    ),
                },
            ),
        ),
    ]
