# Generated by Django 6.0.3 on 2026-03-19 20:15

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0006_alter_testpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("rich_text", 1),
                    ("card", 3),
                    ("hero", 12),
                    ("cta_callout", 15),
                    ("badge", 18),
                    ("cms_button", 23),
                    ("enhanced_hero", 33),
                    ("feature_grid", 44),
                    ("pricing_section", 57),
                    ("stats_section", 64),
                    ("testimonial_section", 72),
                    ("text_with_image", 81),
                    ("logo_cloud", 87),
                    ("cta_banner", 92),
                    ("faq_section", 100),
                    ("footer_section", 110),
                    ("rich_text_section", 113),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.blocks.TextBlock", (), {}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("body", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"max_length": 200}),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 400, "required": False},
                    ),
                    6: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Button text", "max_length": 100},
                    ),
                    8: ("wagtail.blocks.URLBlock", (), {"label": "Button URL"}),
                    9: ("wagtail.blocks.StructBlock", [[("text", 7), ("url", 8)]], {}),
                    10: (
                        "wagtail.blocks.ListBlock",
                        (9,),
                        {
                            "help_text": "Add one or more call-to-action buttons",
                            "label": "Buttons",
                            "max_num": 3,
                            "min_num": 0,
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("buttons", 10)]],
                        {"label": "Call to action", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 4), ("subheading", 5), ("body", 6), ("cta", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("buttons", 10)]],
                        {"label": "Action buttons"},
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("accent", "Accent"),
                            ],
                            "help_text": "Controls the visual style of the callout panel.",
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 4), ("text", 2), ("buttons", 13), ("style", 14)]],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "New Feature", "max_length": 100},
                    ),
                    17: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default"),
                                ("highlight", "Highlight"),
                                ("muted", "Muted"),
                            ]
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 16), ("variant", 17)]],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Get Started", "max_length": 100},
                    ),
                    20: ("wagtail.blocks.URLBlock", (), {"default": "#"}),
                    21: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("outline", "Outline"),
                                ("ghost", "Ghost"),
                            ]
                        },
                    ),
                    22: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Small"),
                                ("md", "Medium"),
                                ("lg", "Large"),
                            ]
                        },
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 19), ("href", 20), ("variant", 21), ("size", 22)]],
                        {},
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Introducing", "max_length": 50, "required": False},
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Build amazing experiences with our platform",
                            "max_length": 200,
                        },
                    ),
                    26: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Powerful tools and features to help you create, manage, and scale your content with ease. Join thousands of teams already using our platform."
                        },
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 19), ("href", 20), ("variant", 21), ("size", 22)]],
                        {"label": "Primary CTA", "required": False},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 19), ("href", 20), ("variant", 21), ("size", 22)]],
                        {"label": "Secondary CTA", "required": False},
                    ),
                    29: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Hero image", "max_length": 255, "required": False},
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 29), ("alt", 30)]],
                        {"label": "Hero Image", "required": False},
                    ),
                    32: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("left", "Left"), ("center", "Center")]},
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 24),
                                ("headline", 25),
                                ("description", 26),
                                ("primary_cta", 27),
                                ("secondary_cta", 28),
                                ("image", 31),
                                ("alignment", 32),
                            ]
                        ],
                        {},
                    ),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Features", "max_length": 50, "required": False},
                    ),
                    35: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Everything you need to succeed",
                            "max_length": 200,
                        },
                    ),
                    36: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Powerful features designed to help you work smarter and faster.",
                            "required": False,
                        },
                    ),
                    37: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("2", "2 columns"),
                                ("3", "3 columns"),
                                ("4", "4 columns"),
                            ]
                        },
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "⚡",
                            "help_text": "Emoji or icon character (e.g., 🚀, ⚡, 💡)",
                            "max_length": 10,
                        },
                    ),
                    39: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Lightning Fast", "max_length": 100},
                    ),
                    40: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Built for speed and performance. Experience instant page loads and seamless interactions."
                        },
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 38), ("title", 39), ("description", 40)]],
                        {},
                    ),
                    42: (
                        "wagtail.blocks.ListBlock",
                        (41,),
                        {"max_num": 12, "min_num": 1},
                    ),
                    43: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default"),
                                ("surface", "Surface"),
                                ("secondary", "Secondary"),
                            ]
                        },
                    ),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 34),
                                ("headline", 35),
                                ("description", 36),
                                ("columns", 37),
                                ("features", 42),
                                ("background", 43),
                            ]
                        ],
                        {},
                    ),
                    45: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Pricing", "max_length": 50, "required": False},
                    ),
                    46: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Choose your plan", "max_length": 200},
                    ),
                    47: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Simple, transparent pricing that grows with you. Try any plan free for 14 days.",
                            "required": False,
                        },
                    ),
                    48: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Professional", "max_length": 100},
                    ),
                    49: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "$29/mo",
                            "help_text": "e.g., $29/mo",
                            "max_length": 50,
                        },
                    ),
                    50: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"default": "Perfect for growing teams and businesses"},
                    ),
                    51: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Unlimited projects", "max_length": 200},
                    ),
                    52: ("wagtail.blocks.ListBlock", (51,), {"label": "Features"}),
                    53: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 19), ("href", 20), ("variant", 21), ("size", 22)]],
                        {"label": "Call to Action"},
                    ),
                    54: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Highlight this plan with special styling",
                            "required": False,
                        },
                    ),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 48),
                                ("price", 49),
                                ("description", 50),
                                ("features", 52),
                                ("cta", 53),
                                ("highlighted", 54),
                            ]
                        ],
                        {},
                    ),
                    56: (
                        "wagtail.blocks.ListBlock",
                        (55,),
                        {"max_num": 4, "min_num": 1},
                    ),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 45),
                                ("headline", 46),
                                ("description", 47),
                                ("plans", 56),
                                ("background", 43),
                            ]
                        ],
                        {},
                    ),
                    58: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "By the numbers",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    59: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Trusted by teams worldwide",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    60: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "99.9%",
                            "help_text": "e.g., 99.9%, 10k+, $1M",
                            "max_length": 50,
                        },
                    ),
                    61: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Uptime", "max_length": 100},
                    ),
                    62: (
                        "wagtail.blocks.StructBlock",
                        [[("value", 60), ("label", 61)]],
                        {},
                    ),
                    63: (
                        "wagtail.blocks.ListBlock",
                        (62,),
                        {"max_num": 8, "min_num": 1},
                    ),
                    64: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 58),
                                ("headline", 59),
                                ("stats", 63),
                                ("background", 43),
                            ]
                        ],
                        {},
                    ),
                    65: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Testimonials",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    66: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Loved by teams everywhere", "max_length": 200},
                    ),
                    67: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "This platform has completely transformed how we work. The tools are intuitive and powerful."
                        },
                    ),
                    68: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Sarah Johnson", "max_length": 100},
                    ),
                    69: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Head of Product, TechCorp", "max_length": 100},
                    ),
                    70: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 67), ("author", 68), ("role", 69), ("avatar", 29)]],
                        {},
                    ),
                    71: (
                        "wagtail.blocks.ListBlock",
                        (70,),
                        {"max_num": 6, "min_num": 1},
                    ),
                    72: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 65),
                                ("headline", 66),
                                ("testimonials", 71),
                                ("background", 43),
                            ]
                        ],
                        {},
                    ),
                    73: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "How it works",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    74: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Built for creators and teams", "max_length": 200},
                    ),
                    75: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Our platform brings together everything you need to create, collaborate, and publish. From idea to execution, we've got you covered with powerful tools designed for modern teams."
                        },
                    ),
                    76: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    77: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Feature illustration",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    78: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 76), ("alt", 77)]],
                        {"label": "Image"},
                    ),
                    79: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("right", "Right")],
                            "label": "Image position",
                        },
                    ),
                    80: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 19), ("href", 20), ("variant", 21), ("size", 22)]],
                        {"label": "Call to Action", "required": False},
                    ),
                    81: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 73),
                                ("headline", 74),
                                ("description", 75),
                                ("image", 78),
                                ("image_position", 79),
                                ("cta", 80),
                                ("background", 43),
                            ]
                        ],
                        {},
                    ),
                    82: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Trusted by leading companies",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    83: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Partner logo", "max_length": 255},
                    ),
                    84: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"default": "#", "label": "Link URL", "required": False},
                    ),
                    85: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 76), ("alt", 83), ("href", 84)]],
                        {},
                    ),
                    86: (
                        "wagtail.blocks.ListBlock",
                        (85,),
                        {"max_num": 12, "min_num": 1},
                    ),
                    87: (
                        "wagtail.blocks.StructBlock",
                        [[("headline", 82), ("logos", 86), ("background", 43)]],
                        {},
                    ),
                    88: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Ready to get started?", "max_length": 200},
                    ),
                    89: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Join thousands of teams already using our platform. Start your free trial today.",
                            "required": False,
                        },
                    ),
                    90: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 19), ("href", 20), ("variant", 21), ("size", 22)]],
                        {"label": "Primary CTA"},
                    ),
                    91: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("default", "Default"), ("primary", "Primary")]},
                    ),
                    92: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("headline", 88),
                                ("description", 89),
                                ("primary_cta", 90),
                                ("secondary_cta", 28),
                                ("variant", 91),
                            ]
                        ],
                        {},
                    ),
                    93: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "FAQ", "max_length": 50, "required": False},
                    ),
                    94: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Frequently asked questions", "max_length": 200},
                    ),
                    95: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Everything you need to know about our platform. Can't find the answer you're looking for? Contact our support team.",
                            "required": False,
                        },
                    ),
                    96: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "How does this work?", "max_length": 200},
                    ),
                    97: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Our platform is designed to be intuitive and easy to use. Simply sign up, create your first project, and start collaborating with your team right away."
                        },
                    ),
                    98: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 96), ("answer", 97)]],
                        {},
                    ),
                    99: (
                        "wagtail.blocks.ListBlock",
                        (98,),
                        {"max_num": 20, "min_num": 1},
                    ),
                    100: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 93),
                                ("headline", 94),
                                ("description", 95),
                                ("faqs", 99),
                                ("background", 43),
                            ]
                        ],
                        {},
                    ),
                    101: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "YourBrand",
                            "help_text": "Brand name or tagline",
                            "max_length": 100,
                        },
                    ),
                    102: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Building the future of content management, one block at a time.",
                            "required": False,
                        },
                    ),
                    103: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Company", "max_length": 100},
                    ),
                    104: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "About Us", "max_length": 100},
                    ),
                    105: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 104), ("url", 20)]],
                        {},
                    ),
                    106: ("wagtail.blocks.ListBlock", (105,), {}),
                    107: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 103), ("links", 106)]],
                        {},
                    ),
                    108: ("wagtail.blocks.ListBlock", (107,), {"max_num": 4}),
                    109: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "© 2026 YourBrand. All rights reserved.",
                            "max_length": 200,
                        },
                    ),
                    110: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("brand_text", 101),
                                ("description", 102),
                                ("columns", 108),
                                ("copyright", 109),
                            ]
                        ],
                        {},
                    ),
                    111: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "<p>Add your content here. This section supports rich text formatting including <strong>bold</strong>, <em>italic</em>, links, lists, and more.</p>"
                        },
                    ),
                    112: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Small (640px)"),
                                ("md", "Medium (768px)"),
                                ("lg", "Large (1024px)"),
                            ]
                        },
                    ),
                    113: (
                        "wagtail.blocks.StructBlock",
                        [[("content", 111), ("max_width", 112), ("background", 43)]],
                        {},
                    ),
                },
            ),
        ),
    ]
