# Generated by Django 6.0.3 on 2026-03-19 20:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0008_alter_testpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("rich_text", 1),
                    ("card", 3),
                    ("hero", 12),
                    ("cta_callout", 17),
                    ("badge", 20),
                    ("cms_button", 25),
                    ("enhanced_hero", 35),
                    ("feature_grid", 46),
                    ("pricing_section", 59),
                    ("stats_section", 66),
                    ("testimonial_section", 74),
                    ("text_with_image", 83),
                    ("logo_cloud", 89),
                    ("cta_banner", 94),
                    ("faq_section", 102),
                    ("footer_section", 112),
                    ("rich_text_section", 115),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.blocks.TextBlock", (), {}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("body", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Welcome to our platform", "max_length": 200},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Discover powerful tools to transform your workflow",
                            "max_length": 400,
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "<p>Start building amazing experiences today with our comprehensive suite of features designed for modern teams.</p>",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Learn More",
                            "label": "Button text",
                            "max_length": 100,
                        },
                    ),
                    8: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"default": "https://example.com", "label": "Button URL"},
                    ),
                    9: ("wagtail.blocks.StructBlock", [[("text", 7), ("url", 8)]], {}),
                    10: (
                        "wagtail.blocks.ListBlock",
                        (9,),
                        {
                            "help_text": "Add one or more call-to-action buttons",
                            "label": "Buttons",
                            "max_num": 3,
                            "min_num": 0,
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("buttons", 10)]],
                        {"label": "Call to action", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 4), ("subheading", 5), ("body", 6), ("cta", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Take action today", "max_length": 200},
                    ),
                    14: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Don't miss out on this opportunity. Get started now and see the difference for yourself."
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("buttons", 10)]],
                        {"label": "Action buttons"},
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("accent", "Accent"),
                            ],
                            "help_text": "Controls the visual style of the callout panel.",
                        },
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 13), ("text", 14), ("buttons", 15), ("style", 16)]],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "New Feature", "max_length": 100},
                    ),
                    19: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default"),
                                ("highlight", "Highlight"),
                                ("muted", "Muted"),
                            ]
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 18), ("variant", 19)]],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Get Started", "max_length": 100},
                    ),
                    22: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"default": "https://example.com"},
                    ),
                    23: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("outline", "Outline"),
                                ("ghost", "Ghost"),
                            ]
                        },
                    ),
                    24: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Small"),
                                ("md", "Medium"),
                                ("lg", "Large"),
                            ]
                        },
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 21), ("href", 22), ("variant", 23), ("size", 24)]],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Introducing", "max_length": 50, "required": False},
                    ),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Build amazing experiences with our platform",
                            "max_length": 200,
                        },
                    ),
                    28: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Powerful tools and features to help you create, manage, and scale your content with ease. Join thousands of teams already using our platform."
                        },
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 21), ("href", 22), ("variant", 23), ("size", 24)]],
                        {"label": "Primary CTA", "required": False},
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 21), ("href", 22), ("variant", 23), ("size", 24)]],
                        {"label": "Secondary CTA", "required": False},
                    ),
                    31: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Hero image", "max_length": 255, "required": False},
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 31), ("alt", 32)]],
                        {"label": "Hero Image", "required": False},
                    ),
                    34: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("left", "Left"), ("center", "Center")]},
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 26),
                                ("headline", 27),
                                ("description", 28),
                                ("primary_cta", 29),
                                ("secondary_cta", 30),
                                ("image", 33),
                                ("alignment", 34),
                            ]
                        ],
                        {},
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Features", "max_length": 50, "required": False},
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Everything you need to succeed",
                            "max_length": 200,
                        },
                    ),
                    38: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Powerful features designed to help you work smarter and faster.",
                            "required": False,
                        },
                    ),
                    39: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("2", "2 columns"),
                                ("3", "3 columns"),
                                ("4", "4 columns"),
                            ]
                        },
                    ),
                    40: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "⚡",
                            "help_text": "Emoji or icon character (e.g., 🚀, ⚡, 💡)",
                            "max_length": 10,
                        },
                    ),
                    41: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Lightning Fast", "max_length": 100},
                    ),
                    42: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Built for speed and performance. Experience instant page loads and seamless interactions."
                        },
                    ),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 40), ("title", 41), ("description", 42)]],
                        {},
                    ),
                    44: (
                        "wagtail.blocks.ListBlock",
                        (43,),
                        {"max_num": 12, "min_num": 1},
                    ),
                    45: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default"),
                                ("surface", "Surface"),
                                ("secondary", "Secondary"),
                            ]
                        },
                    ),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 36),
                                ("headline", 37),
                                ("description", 38),
                                ("columns", 39),
                                ("features", 44),
                                ("background", 45),
                            ]
                        ],
                        {},
                    ),
                    47: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Pricing", "max_length": 50, "required": False},
                    ),
                    48: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Choose your plan", "max_length": 200},
                    ),
                    49: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Simple, transparent pricing that grows with you. Try any plan free for 14 days.",
                            "required": False,
                        },
                    ),
                    50: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Professional", "max_length": 100},
                    ),
                    51: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "$29/mo",
                            "help_text": "e.g., $29/mo",
                            "max_length": 50,
                        },
                    ),
                    52: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"default": "Perfect for growing teams and businesses"},
                    ),
                    53: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Unlimited projects", "max_length": 200},
                    ),
                    54: ("wagtail.blocks.ListBlock", (53,), {"label": "Features"}),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 21), ("href", 22), ("variant", 23), ("size", 24)]],
                        {"label": "Call to Action"},
                    ),
                    56: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Highlight this plan with special styling",
                            "required": False,
                        },
                    ),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 50),
                                ("price", 51),
                                ("description", 52),
                                ("features", 54),
                                ("cta", 55),
                                ("highlighted", 56),
                            ]
                        ],
                        {},
                    ),
                    58: (
                        "wagtail.blocks.ListBlock",
                        (57,),
                        {"max_num": 4, "min_num": 1},
                    ),
                    59: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 47),
                                ("headline", 48),
                                ("description", 49),
                                ("plans", 58),
                                ("background", 45),
                            ]
                        ],
                        {},
                    ),
                    60: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "By the numbers",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    61: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Trusted by teams worldwide",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    62: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "99.9%",
                            "help_text": "e.g., 99.9%, 10k+, $1M",
                            "max_length": 50,
                        },
                    ),
                    63: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Uptime", "max_length": 100},
                    ),
                    64: (
                        "wagtail.blocks.StructBlock",
                        [[("value", 62), ("label", 63)]],
                        {},
                    ),
                    65: (
                        "wagtail.blocks.ListBlock",
                        (64,),
                        {"max_num": 8, "min_num": 1},
                    ),
                    66: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 60),
                                ("headline", 61),
                                ("stats", 65),
                                ("background", 45),
                            ]
                        ],
                        {},
                    ),
                    67: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Testimonials",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    68: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Loved by teams everywhere", "max_length": 200},
                    ),
                    69: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "This platform has completely transformed how we work. The tools are intuitive and powerful."
                        },
                    ),
                    70: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Sarah Johnson", "max_length": 100},
                    ),
                    71: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Head of Product, TechCorp", "max_length": 100},
                    ),
                    72: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 69), ("author", 70), ("role", 71), ("avatar", 31)]],
                        {},
                    ),
                    73: (
                        "wagtail.blocks.ListBlock",
                        (72,),
                        {"max_num": 6, "min_num": 1},
                    ),
                    74: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 67),
                                ("headline", 68),
                                ("testimonials", 73),
                                ("background", 45),
                            ]
                        ],
                        {},
                    ),
                    75: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "How it works",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    76: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Built for creators and teams", "max_length": 200},
                    ),
                    77: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Our platform brings together everything you need to create, collaborate, and publish. From idea to execution, we've got you covered with powerful tools designed for modern teams."
                        },
                    ),
                    78: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    79: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Feature illustration",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    80: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 78), ("alt", 79)]],
                        {"label": "Image"},
                    ),
                    81: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("right", "Right")],
                            "label": "Image position",
                        },
                    ),
                    82: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 21), ("href", 22), ("variant", 23), ("size", 24)]],
                        {"label": "Call to Action", "required": False},
                    ),
                    83: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 75),
                                ("headline", 76),
                                ("description", 77),
                                ("image", 80),
                                ("image_position", 81),
                                ("cta", 82),
                                ("background", 45),
                            ]
                        ],
                        {},
                    ),
                    84: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Trusted by leading companies",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    85: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Partner logo", "max_length": 255},
                    ),
                    86: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "https://example.com",
                            "label": "Link URL",
                            "required": False,
                        },
                    ),
                    87: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 78), ("alt", 85), ("href", 86)]],
                        {},
                    ),
                    88: (
                        "wagtail.blocks.ListBlock",
                        (87,),
                        {"max_num": 12, "min_num": 1},
                    ),
                    89: (
                        "wagtail.blocks.StructBlock",
                        [[("headline", 84), ("logos", 88), ("background", 45)]],
                        {},
                    ),
                    90: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Ready to get started?", "max_length": 200},
                    ),
                    91: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Join thousands of teams already using our platform. Start your free trial today.",
                            "required": False,
                        },
                    ),
                    92: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 21), ("href", 22), ("variant", 23), ("size", 24)]],
                        {"label": "Primary CTA"},
                    ),
                    93: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("default", "Default"), ("primary", "Primary")]},
                    ),
                    94: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("headline", 90),
                                ("description", 91),
                                ("primary_cta", 92),
                                ("secondary_cta", 30),
                                ("variant", 93),
                            ]
                        ],
                        {},
                    ),
                    95: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "FAQ", "max_length": 50, "required": False},
                    ),
                    96: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Frequently asked questions", "max_length": 200},
                    ),
                    97: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Everything you need to know about our platform. Can't find the answer you're looking for? Contact our support team.",
                            "required": False,
                        },
                    ),
                    98: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "How does this work?", "max_length": 200},
                    ),
                    99: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Our platform is designed to be intuitive and easy to use. Simply sign up, create your first project, and start collaborating with your team right away."
                        },
                    ),
                    100: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 98), ("answer", 99)]],
                        {},
                    ),
                    101: (
                        "wagtail.blocks.ListBlock",
                        (100,),
                        {"max_num": 20, "min_num": 1},
                    ),
                    102: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 95),
                                ("headline", 96),
                                ("description", 97),
                                ("faqs", 101),
                                ("background", 45),
                            ]
                        ],
                        {},
                    ),
                    103: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "YourBrand",
                            "help_text": "Brand name or tagline",
                            "max_length": 100,
                        },
                    ),
                    104: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Building the future of content management, one block at a time.",
                            "required": False,
                        },
                    ),
                    105: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Company", "max_length": 100},
                    ),
                    106: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "About Us", "max_length": 100},
                    ),
                    107: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 106), ("url", 22)]],
                        {},
                    ),
                    108: ("wagtail.blocks.ListBlock", (107,), {}),
                    109: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 105), ("links", 108)]],
                        {},
                    ),
                    110: ("wagtail.blocks.ListBlock", (109,), {"max_num": 4}),
                    111: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "© 2026 YourBrand. All rights reserved.",
                            "max_length": 200,
                        },
                    ),
                    112: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("brand_text", 103),
                                ("description", 104),
                                ("columns", 110),
                                ("copyright", 111),
                            ]
                        ],
                        {},
                    ),
                    113: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "<p>Add your content here. This section supports rich text formatting including <strong>bold</strong>, <em>italic</em>, links, lists, and more.</p>"
                        },
                    ),
                    114: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Small (640px)"),
                                ("md", "Medium (768px)"),
                                ("lg", "Large (1024px)"),
                            ]
                        },
                    ),
                    115: (
                        "wagtail.blocks.StructBlock",
                        [[("content", 113), ("max_width", 114), ("background", 45)]],
                        {},
                    ),
                },
            ),
        ),
    ]
