# Generated by Django 6.0.3 on 2026-03-19 22:27

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0009_alter_testpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("rich_text", 1),
                    ("card", 3),
                    ("hero", 12),
                    ("badge", 15),
                    ("cms_button", 20),
                    ("enhanced_hero", 30),
                    ("feature_grid", 41),
                    ("pricing_section", 54),
                    ("stats_section", 61),
                    ("testimonial_section", 69),
                    ("text_with_image", 78),
                    ("logo_cloud", 84),
                    ("cta_banner", 89),
                    ("faq_section", 97),
                    ("footer_section", 107),
                    ("rich_text_section", 110),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.blocks.TextBlock", (), {}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("body", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Welcome to our platform", "max_length": 200},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Discover powerful tools to transform your workflow",
                            "max_length": 400,
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "<p>Start building amazing experiences today with our comprehensive suite of features designed for modern teams.</p>",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Learn More",
                            "label": "Button text",
                            "max_length": 100,
                        },
                    ),
                    8: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"default": "https://example.com", "label": "Button URL"},
                    ),
                    9: ("wagtail.blocks.StructBlock", [[("text", 7), ("url", 8)]], {}),
                    10: (
                        "wagtail.blocks.ListBlock",
                        (9,),
                        {
                            "help_text": "Add one or more call-to-action buttons",
                            "label": "Buttons",
                            "max_num": 3,
                            "min_num": 0,
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("buttons", 10)]],
                        {"label": "Call to action", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 4), ("subheading", 5), ("body", 6), ("cta", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "New Feature", "max_length": 100},
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default"),
                                ("highlight", "Highlight"),
                                ("muted", "Muted"),
                            ]
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 13), ("variant", 14)]],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Get Started", "max_length": 100},
                    ),
                    17: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"default": "https://example.com"},
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("outline", "Outline"),
                                ("ghost", "Ghost"),
                            ]
                        },
                    ),
                    19: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Small"),
                                ("md", "Medium"),
                                ("lg", "Large"),
                            ]
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 16), ("href", 17), ("variant", 18), ("size", 19)]],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Introducing", "max_length": 50, "required": False},
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Build amazing experiences with our platform",
                            "max_length": 200,
                        },
                    ),
                    23: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Powerful tools and features to help you create, manage, and scale your content with ease. Join thousands of teams already using our platform."
                        },
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 16), ("href", 17), ("variant", 18), ("size", 19)]],
                        {"label": "Primary CTA", "required": False},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 16), ("href", 17), ("variant", 18), ("size", 19)]],
                        {"label": "Secondary CTA", "required": False},
                    ),
                    26: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Hero image", "max_length": 255, "required": False},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 26), ("alt", 27)]],
                        {"label": "Hero Image", "required": False},
                    ),
                    29: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("left", "Left"), ("center", "Center")]},
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 21),
                                ("headline", 22),
                                ("description", 23),
                                ("primary_cta", 24),
                                ("secondary_cta", 25),
                                ("image", 28),
                                ("alignment", 29),
                            ]
                        ],
                        {},
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Features", "max_length": 50, "required": False},
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Everything you need to succeed",
                            "max_length": 200,
                        },
                    ),
                    33: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Powerful features designed to help you work smarter and faster.",
                            "required": False,
                        },
                    ),
                    34: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("2", "2 columns"),
                                ("3", "3 columns"),
                                ("4", "4 columns"),
                            ]
                        },
                    ),
                    35: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "⚡",
                            "help_text": "Emoji or icon character (e.g., 🚀, ⚡, 💡)",
                            "max_length": 10,
                        },
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Lightning Fast", "max_length": 100},
                    ),
                    37: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Built for speed and performance. Experience instant page loads and seamless interactions."
                        },
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 35), ("title", 36), ("description", 37)]],
                        {},
                    ),
                    39: (
                        "wagtail.blocks.ListBlock",
                        (38,),
                        {"max_num": 12, "min_num": 1},
                    ),
                    40: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default"),
                                ("surface", "Surface"),
                                ("secondary", "Secondary"),
                            ]
                        },
                    ),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 31),
                                ("headline", 32),
                                ("description", 33),
                                ("columns", 34),
                                ("features", 39),
                                ("background", 40),
                            ]
                        ],
                        {},
                    ),
                    42: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Pricing", "max_length": 50, "required": False},
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Choose your plan", "max_length": 200},
                    ),
                    44: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Simple, transparent pricing that grows with you. Try any plan free for 14 days.",
                            "required": False,
                        },
                    ),
                    45: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Professional", "max_length": 100},
                    ),
                    46: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "$29/mo",
                            "help_text": "e.g., $29/mo",
                            "max_length": 50,
                        },
                    ),
                    47: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"default": "Perfect for growing teams and businesses"},
                    ),
                    48: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Unlimited projects", "max_length": 200},
                    ),
                    49: ("wagtail.blocks.ListBlock", (48,), {"label": "Features"}),
                    50: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 16), ("href", 17), ("variant", 18), ("size", 19)]],
                        {"label": "Call to Action"},
                    ),
                    51: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Highlight this plan with special styling",
                            "required": False,
                        },
                    ),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 45),
                                ("price", 46),
                                ("description", 47),
                                ("features", 49),
                                ("cta", 50),
                                ("highlighted", 51),
                            ]
                        ],
                        {},
                    ),
                    53: (
                        "wagtail.blocks.ListBlock",
                        (52,),
                        {"max_num": 4, "min_num": 1},
                    ),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 42),
                                ("headline", 43),
                                ("description", 44),
                                ("plans", 53),
                                ("background", 40),
                            ]
                        ],
                        {},
                    ),
                    55: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "By the numbers",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    56: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Trusted by teams worldwide",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    57: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "99.9%",
                            "help_text": "e.g., 99.9%, 10k+, $1M",
                            "max_length": 50,
                        },
                    ),
                    58: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Uptime", "max_length": 100},
                    ),
                    59: (
                        "wagtail.blocks.StructBlock",
                        [[("value", 57), ("label", 58)]],
                        {},
                    ),
                    60: (
                        "wagtail.blocks.ListBlock",
                        (59,),
                        {"max_num": 8, "min_num": 1},
                    ),
                    61: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 55),
                                ("headline", 56),
                                ("stats", 60),
                                ("background", 40),
                            ]
                        ],
                        {},
                    ),
                    62: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Testimonials",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    63: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Loved by teams everywhere", "max_length": 200},
                    ),
                    64: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "This platform has completely transformed how we work. The tools are intuitive and powerful."
                        },
                    ),
                    65: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Sarah Johnson", "max_length": 100},
                    ),
                    66: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Head of Product, TechCorp", "max_length": 100},
                    ),
                    67: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 64), ("author", 65), ("role", 66), ("avatar", 26)]],
                        {},
                    ),
                    68: (
                        "wagtail.blocks.ListBlock",
                        (67,),
                        {"max_num": 6, "min_num": 1},
                    ),
                    69: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 62),
                                ("headline", 63),
                                ("testimonials", 68),
                                ("background", 40),
                            ]
                        ],
                        {},
                    ),
                    70: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "How it works",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    71: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Built for creators and teams", "max_length": 200},
                    ),
                    72: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Our platform brings together everything you need to create, collaborate, and publish. From idea to execution, we've got you covered with powerful tools designed for modern teams."
                        },
                    ),
                    73: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    74: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Feature illustration",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    75: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 73), ("alt", 74)]],
                        {"label": "Image"},
                    ),
                    76: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("right", "Right")],
                            "label": "Image position",
                        },
                    ),
                    77: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 16), ("href", 17), ("variant", 18), ("size", 19)]],
                        {"label": "Call to Action", "required": False},
                    ),
                    78: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 70),
                                ("headline", 71),
                                ("description", 72),
                                ("image", 75),
                                ("image_position", 76),
                                ("cta", 77),
                                ("background", 40),
                            ]
                        ],
                        {},
                    ),
                    79: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Trusted by leading companies",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    80: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Partner logo", "max_length": 255},
                    ),
                    81: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "https://example.com",
                            "label": "Link URL",
                            "required": False,
                        },
                    ),
                    82: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 73), ("alt", 80), ("href", 81)]],
                        {},
                    ),
                    83: (
                        "wagtail.blocks.ListBlock",
                        (82,),
                        {"max_num": 12, "min_num": 1},
                    ),
                    84: (
                        "wagtail.blocks.StructBlock",
                        [[("headline", 79), ("logos", 83), ("background", 40)]],
                        {},
                    ),
                    85: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Ready to get started?", "max_length": 200},
                    ),
                    86: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Join thousands of teams already using our platform. Start your free trial today.",
                            "required": False,
                        },
                    ),
                    87: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 16), ("href", 17), ("variant", 18), ("size", 19)]],
                        {"label": "Primary CTA"},
                    ),
                    88: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("default", "Default"), ("primary", "Primary")]},
                    ),
                    89: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("headline", 85),
                                ("description", 86),
                                ("primary_cta", 87),
                                ("secondary_cta", 25),
                                ("variant", 88),
                            ]
                        ],
                        {},
                    ),
                    90: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "FAQ", "max_length": 50, "required": False},
                    ),
                    91: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Frequently asked questions", "max_length": 200},
                    ),
                    92: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Everything you need to know about our platform. Can't find the answer you're looking for? Contact our support team.",
                            "required": False,
                        },
                    ),
                    93: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "How does this work?", "max_length": 200},
                    ),
                    94: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Our platform is designed to be intuitive and easy to use. Simply sign up, create your first project, and start collaborating with your team right away."
                        },
                    ),
                    95: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 93), ("answer", 94)]],
                        {},
                    ),
                    96: (
                        "wagtail.blocks.ListBlock",
                        (95,),
                        {"max_num": 20, "min_num": 1},
                    ),
                    97: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 90),
                                ("headline", 91),
                                ("description", 92),
                                ("faqs", 96),
                                ("background", 40),
                            ]
                        ],
                        {},
                    ),
                    98: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "YourBrand",
                            "help_text": "Brand name or tagline",
                            "max_length": 100,
                        },
                    ),
                    99: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Building the future of content management, one block at a time.",
                            "required": False,
                        },
                    ),
                    100: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Company", "max_length": 100},
                    ),
                    101: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "About Us", "max_length": 100},
                    ),
                    102: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 101), ("url", 17)]],
                        {},
                    ),
                    103: ("wagtail.blocks.ListBlock", (102,), {}),
                    104: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 100), ("links", 103)]],
                        {},
                    ),
                    105: ("wagtail.blocks.ListBlock", (104,), {"max_num": 4}),
                    106: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "© 2026 YourBrand. All rights reserved.",
                            "max_length": 200,
                        },
                    ),
                    107: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("brand_text", 98),
                                ("description", 99),
                                ("columns", 105),
                                ("copyright", 106),
                            ]
                        ],
                        {},
                    ),
                    108: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "<p>Add your content here. This section supports rich text formatting including <strong>bold</strong>, <em>italic</em>, links, lists, and more.</p>"
                        },
                    ),
                    109: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Small (640px)"),
                                ("md", "Medium (768px)"),
                                ("lg", "Large (1024px)"),
                            ]
                        },
                    ),
                    110: (
                        "wagtail.blocks.StructBlock",
                        [[("content", 108), ("max_width", 109), ("background", 40)]],
                        {},
                    ),
                },
            ),
        ),
    ]
