# Generated by Django 6.0.3 on 2026-03-19 22:28

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0010_remove_cta_callout_block"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("rich_text", 1),
                    ("hero", 10),
                    ("badge", 13),
                    ("cms_button", 18),
                    ("enhanced_hero", 28),
                    ("feature_grid", 39),
                    ("pricing_section", 52),
                    ("stats_section", 59),
                    ("testimonial_section", 67),
                    ("text_with_image", 76),
                    ("logo_cloud", 82),
                    ("cta_banner", 87),
                    ("faq_section", 95),
                    ("footer_section", 105),
                    ("rich_text_section", 108),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Welcome to our platform", "max_length": 200},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Discover powerful tools to transform your workflow",
                            "max_length": 400,
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "<p>Start building amazing experiences today with our comprehensive suite of features designed for modern teams.</p>",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Learn More",
                            "label": "Button text",
                            "max_length": 100,
                        },
                    ),
                    6: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"default": "https://example.com", "label": "Button URL"},
                    ),
                    7: ("wagtail.blocks.StructBlock", [[("text", 5), ("url", 6)]], {}),
                    8: (
                        "wagtail.blocks.ListBlock",
                        (7,),
                        {
                            "help_text": "Add one or more call-to-action buttons",
                            "label": "Buttons",
                            "max_num": 3,
                            "min_num": 0,
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("buttons", 8)]],
                        {"label": "Call to action", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 2), ("subheading", 3), ("body", 4), ("cta", 9)]],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "New Feature", "max_length": 100},
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default"),
                                ("highlight", "Highlight"),
                                ("muted", "Muted"),
                            ]
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 11), ("variant", 12)]],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Get Started", "max_length": 100},
                    ),
                    15: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"default": "https://example.com"},
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("outline", "Outline"),
                                ("ghost", "Ghost"),
                            ]
                        },
                    ),
                    17: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Small"),
                                ("md", "Medium"),
                                ("lg", "Large"),
                            ]
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 14), ("href", 15), ("variant", 16), ("size", 17)]],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Introducing", "max_length": 50, "required": False},
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Build amazing experiences with our platform",
                            "max_length": 200,
                        },
                    ),
                    21: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Powerful tools and features to help you create, manage, and scale your content with ease. Join thousands of teams already using our platform."
                        },
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 14), ("href", 15), ("variant", 16), ("size", 17)]],
                        {"label": "Primary CTA", "required": False},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 14), ("href", 15), ("variant", 16), ("size", 17)]],
                        {"label": "Secondary CTA", "required": False},
                    ),
                    24: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Hero image", "max_length": 255, "required": False},
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 24), ("alt", 25)]],
                        {"label": "Hero Image", "required": False},
                    ),
                    27: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("left", "Left"), ("center", "Center")]},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 19),
                                ("headline", 20),
                                ("description", 21),
                                ("primary_cta", 22),
                                ("secondary_cta", 23),
                                ("image", 26),
                                ("alignment", 27),
                            ]
                        ],
                        {},
                    ),
                    29: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Features", "max_length": 50, "required": False},
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Everything you need to succeed",
                            "max_length": 200,
                        },
                    ),
                    31: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Powerful features designed to help you work smarter and faster.",
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("2", "2 columns"),
                                ("3", "3 columns"),
                                ("4", "4 columns"),
                            ]
                        },
                    ),
                    33: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "⚡",
                            "help_text": "Emoji or icon character (e.g., 🚀, ⚡, 💡)",
                            "max_length": 10,
                        },
                    ),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Lightning Fast", "max_length": 100},
                    ),
                    35: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Built for speed and performance. Experience instant page loads and seamless interactions."
                        },
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 33), ("title", 34), ("description", 35)]],
                        {},
                    ),
                    37: (
                        "wagtail.blocks.ListBlock",
                        (36,),
                        {"max_num": 12, "min_num": 1},
                    ),
                    38: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default"),
                                ("surface", "Surface"),
                                ("secondary", "Secondary"),
                            ]
                        },
                    ),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 29),
                                ("headline", 30),
                                ("description", 31),
                                ("columns", 32),
                                ("features", 37),
                                ("background", 38),
                            ]
                        ],
                        {},
                    ),
                    40: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Pricing", "max_length": 50, "required": False},
                    ),
                    41: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Choose your plan", "max_length": 200},
                    ),
                    42: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Simple, transparent pricing that grows with you. Try any plan free for 14 days.",
                            "required": False,
                        },
                    ),
                    43: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Professional", "max_length": 100},
                    ),
                    44: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "$29/mo",
                            "help_text": "e.g., $29/mo",
                            "max_length": 50,
                        },
                    ),
                    45: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"default": "Perfect for growing teams and businesses"},
                    ),
                    46: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Unlimited projects", "max_length": 200},
                    ),
                    47: ("wagtail.blocks.ListBlock", (46,), {"label": "Features"}),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 14), ("href", 15), ("variant", 16), ("size", 17)]],
                        {"label": "Call to Action"},
                    ),
                    49: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Highlight this plan with special styling",
                            "required": False,
                        },
                    ),
                    50: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 43),
                                ("price", 44),
                                ("description", 45),
                                ("features", 47),
                                ("cta", 48),
                                ("highlighted", 49),
                            ]
                        ],
                        {},
                    ),
                    51: (
                        "wagtail.blocks.ListBlock",
                        (50,),
                        {"max_num": 4, "min_num": 1},
                    ),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 40),
                                ("headline", 41),
                                ("description", 42),
                                ("plans", 51),
                                ("background", 38),
                            ]
                        ],
                        {},
                    ),
                    53: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "By the numbers",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    54: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Trusted by teams worldwide",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    55: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "99.9%",
                            "help_text": "e.g., 99.9%, 10k+, $1M",
                            "max_length": 50,
                        },
                    ),
                    56: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Uptime", "max_length": 100},
                    ),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [[("value", 55), ("label", 56)]],
                        {},
                    ),
                    58: (
                        "wagtail.blocks.ListBlock",
                        (57,),
                        {"max_num": 8, "min_num": 1},
                    ),
                    59: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 53),
                                ("headline", 54),
                                ("stats", 58),
                                ("background", 38),
                            ]
                        ],
                        {},
                    ),
                    60: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Testimonials",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    61: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Loved by teams everywhere", "max_length": 200},
                    ),
                    62: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "This platform has completely transformed how we work. The tools are intuitive and powerful."
                        },
                    ),
                    63: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Sarah Johnson", "max_length": 100},
                    ),
                    64: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Head of Product, TechCorp", "max_length": 100},
                    ),
                    65: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 62), ("author", 63), ("role", 64), ("avatar", 24)]],
                        {},
                    ),
                    66: (
                        "wagtail.blocks.ListBlock",
                        (65,),
                        {"max_num": 6, "min_num": 1},
                    ),
                    67: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 60),
                                ("headline", 61),
                                ("testimonials", 66),
                                ("background", 38),
                            ]
                        ],
                        {},
                    ),
                    68: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "How it works",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    69: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Built for creators and teams", "max_length": 200},
                    ),
                    70: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Our platform brings together everything you need to create, collaborate, and publish. From idea to execution, we've got you covered with powerful tools designed for modern teams."
                        },
                    ),
                    71: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    72: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Feature illustration",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    73: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 71), ("alt", 72)]],
                        {"label": "Image"},
                    ),
                    74: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("right", "Right")],
                            "label": "Image position",
                        },
                    ),
                    75: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 14), ("href", 15), ("variant", 16), ("size", 17)]],
                        {"label": "Call to Action", "required": False},
                    ),
                    76: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 68),
                                ("headline", 69),
                                ("description", 70),
                                ("image", 73),
                                ("image_position", 74),
                                ("cta", 75),
                                ("background", 38),
                            ]
                        ],
                        {},
                    ),
                    77: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Trusted by leading companies",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    78: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Partner logo", "max_length": 255},
                    ),
                    79: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "https://example.com",
                            "label": "Link URL",
                            "required": False,
                        },
                    ),
                    80: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 71), ("alt", 78), ("href", 79)]],
                        {},
                    ),
                    81: (
                        "wagtail.blocks.ListBlock",
                        (80,),
                        {"max_num": 12, "min_num": 1},
                    ),
                    82: (
                        "wagtail.blocks.StructBlock",
                        [[("headline", 77), ("logos", 81), ("background", 38)]],
                        {},
                    ),
                    83: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Ready to get started?", "max_length": 200},
                    ),
                    84: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Join thousands of teams already using our platform. Start your free trial today.",
                            "required": False,
                        },
                    ),
                    85: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 14), ("href", 15), ("variant", 16), ("size", 17)]],
                        {"label": "Primary CTA"},
                    ),
                    86: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("default", "Default"), ("primary", "Primary")]},
                    ),
                    87: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("headline", 83),
                                ("description", 84),
                                ("primary_cta", 85),
                                ("secondary_cta", 23),
                                ("variant", 86),
                            ]
                        ],
                        {},
                    ),
                    88: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "FAQ", "max_length": 50, "required": False},
                    ),
                    89: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Frequently asked questions", "max_length": 200},
                    ),
                    90: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Everything you need to know about our platform. Can't find the answer you're looking for? Contact our support team.",
                            "required": False,
                        },
                    ),
                    91: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "How does this work?", "max_length": 200},
                    ),
                    92: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Our platform is designed to be intuitive and easy to use. Simply sign up, create your first project, and start collaborating with your team right away."
                        },
                    ),
                    93: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 91), ("answer", 92)]],
                        {},
                    ),
                    94: (
                        "wagtail.blocks.ListBlock",
                        (93,),
                        {"max_num": 20, "min_num": 1},
                    ),
                    95: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 88),
                                ("headline", 89),
                                ("description", 90),
                                ("faqs", 94),
                                ("background", 38),
                            ]
                        ],
                        {},
                    ),
                    96: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "YourBrand",
                            "help_text": "Brand name or tagline",
                            "max_length": 100,
                        },
                    ),
                    97: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Building the future of content management, one block at a time.",
                            "required": False,
                        },
                    ),
                    98: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Company", "max_length": 100},
                    ),
                    99: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "About Us", "max_length": 100},
                    ),
                    100: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 99), ("url", 15)]],
                        {},
                    ),
                    101: ("wagtail.blocks.ListBlock", (100,), {}),
                    102: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 98), ("links", 101)]],
                        {},
                    ),
                    103: ("wagtail.blocks.ListBlock", (102,), {"max_num": 4}),
                    104: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "© 2026 YourBrand. All rights reserved.",
                            "max_length": 200,
                        },
                    ),
                    105: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("brand_text", 96),
                                ("description", 97),
                                ("columns", 103),
                                ("copyright", 104),
                            ]
                        ],
                        {},
                    ),
                    106: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "<p>Add your content here. This section supports rich text formatting including <strong>bold</strong>, <em>italic</em>, links, lists, and more.</p>"
                        },
                    ),
                    107: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Small (640px)"),
                                ("md", "Medium (768px)"),
                                ("lg", "Large (1024px)"),
                            ]
                        },
                    ),
                    108: (
                        "wagtail.blocks.StructBlock",
                        [[("content", 106), ("max_width", 107), ("background", 38)]],
                        {},
                    ),
                },
            ),
        ),
    ]
