# Generated by Django 6.0.3 on 2026-03-19 23:47

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0011_remove_card_block"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("rich_text", 1),
                    ("hero", 9),
                    ("badge", 12),
                    ("cms_button", 17),
                    ("enhanced_hero", 26),
                    ("feature_grid", 37),
                    ("pricing_section", 50),
                    ("stats_section", 57),
                    ("testimonial_section", 65),
                    ("text_with_image", 74),
                    ("logo_cloud", 80),
                    ("cta_banner", 86),
                    ("faq_section", 94),
                    ("footer_section", 104),
                    ("rich_text_section", 107),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Welcome to our platform", "max_length": 200},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Discover powerful tools to transform your workflow",
                            "max_length": 400,
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "<p>Start building amazing experiences today with our comprehensive suite of features designed for modern teams.</p>",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Learn More",
                            "label": "Button text",
                            "max_length": 100,
                        },
                    ),
                    6: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"default": "https://example.com", "label": "Button URL"},
                    ),
                    7: ("wagtail.blocks.StructBlock", [[("text", 5), ("url", 6)]], {}),
                    8: (
                        "wagtail.blocks.ListBlock",
                        (7,),
                        {"label": "Buttons", "max_num": 2, "min_num": 0},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 2),
                                ("subheading", 3),
                                ("body", 4),
                                ("buttons", 8),
                            ]
                        ],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "New Feature", "max_length": 100},
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default"),
                                ("highlight", "Highlight"),
                                ("muted", "Muted"),
                            ]
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 10), ("variant", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Get Started", "max_length": 100},
                    ),
                    14: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"default": "https://example.com"},
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("outline", "Outline"),
                                ("ghost", "Ghost"),
                            ]
                        },
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Small"),
                                ("md", "Medium"),
                                ("lg", "Large"),
                            ]
                        },
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 13), ("href", 14), ("variant", 15), ("size", 16)]],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Introducing", "max_length": 50, "required": False},
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Build amazing experiences with our platform",
                            "max_length": 200,
                        },
                    ),
                    20: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Powerful tools and features to help you create, manage, and scale your content with ease. Join thousands of teams already using our platform."
                        },
                    ),
                    21: (
                        "wagtail.blocks.ListBlock",
                        (17,),
                        {"label": "Buttons", "max_num": 2, "min_num": 0},
                    ),
                    22: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Hero image", "max_length": 255, "required": False},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 22), ("alt", 23)]],
                        {"label": "Hero Image", "required": False},
                    ),
                    25: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("left", "Left"), ("center", "Center")]},
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 18),
                                ("headline", 19),
                                ("description", 20),
                                ("buttons", 21),
                                ("image", 24),
                                ("alignment", 25),
                            ]
                        ],
                        {},
                    ),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Features", "max_length": 50, "required": False},
                    ),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Everything you need to succeed",
                            "max_length": 200,
                        },
                    ),
                    29: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Powerful features designed to help you work smarter and faster.",
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("2", "2 columns"),
                                ("3", "3 columns"),
                                ("4", "4 columns"),
                            ]
                        },
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "⚡",
                            "help_text": "Emoji or icon character (e.g., 🚀, ⚡, 💡)",
                            "max_length": 10,
                        },
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Lightning Fast", "max_length": 100},
                    ),
                    33: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Built for speed and performance. Experience instant page loads and seamless interactions."
                        },
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 31), ("title", 32), ("description", 33)]],
                        {},
                    ),
                    35: (
                        "wagtail.blocks.ListBlock",
                        (34,),
                        {"max_num": 12, "min_num": 1},
                    ),
                    36: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default"),
                                ("surface", "Surface"),
                                ("secondary", "Secondary"),
                            ]
                        },
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 27),
                                ("headline", 28),
                                ("description", 29),
                                ("columns", 30),
                                ("features", 35),
                                ("background", 36),
                            ]
                        ],
                        {},
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Pricing", "max_length": 50, "required": False},
                    ),
                    39: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Choose your plan", "max_length": 200},
                    ),
                    40: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Simple, transparent pricing that grows with you. Try any plan free for 14 days.",
                            "required": False,
                        },
                    ),
                    41: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Professional", "max_length": 100},
                    ),
                    42: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "$29/mo",
                            "help_text": "e.g., $29/mo",
                            "max_length": 50,
                        },
                    ),
                    43: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"default": "Perfect for growing teams and businesses"},
                    ),
                    44: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Unlimited projects", "max_length": 200},
                    ),
                    45: ("wagtail.blocks.ListBlock", (44,), {"label": "Features"}),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 13), ("href", 14), ("variant", 15), ("size", 16)]],
                        {"label": "Call to Action"},
                    ),
                    47: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Highlight this plan with special styling",
                            "required": False,
                        },
                    ),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 41),
                                ("price", 42),
                                ("description", 43),
                                ("features", 45),
                                ("cta", 46),
                                ("highlighted", 47),
                            ]
                        ],
                        {},
                    ),
                    49: (
                        "wagtail.blocks.ListBlock",
                        (48,),
                        {"max_num": 4, "min_num": 1},
                    ),
                    50: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 38),
                                ("headline", 39),
                                ("description", 40),
                                ("plans", 49),
                                ("background", 36),
                            ]
                        ],
                        {},
                    ),
                    51: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "By the numbers",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    52: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Trusted by teams worldwide",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    53: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "99.9%",
                            "help_text": "e.g., 99.9%, 10k+, $1M",
                            "max_length": 50,
                        },
                    ),
                    54: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Uptime", "max_length": 100},
                    ),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [[("value", 53), ("label", 54)]],
                        {},
                    ),
                    56: (
                        "wagtail.blocks.ListBlock",
                        (55,),
                        {"max_num": 8, "min_num": 1},
                    ),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 51),
                                ("headline", 52),
                                ("stats", 56),
                                ("background", 36),
                            ]
                        ],
                        {},
                    ),
                    58: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Testimonials",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    59: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Loved by teams everywhere", "max_length": 200},
                    ),
                    60: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "This platform has completely transformed how we work. The tools are intuitive and powerful."
                        },
                    ),
                    61: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Sarah Johnson", "max_length": 100},
                    ),
                    62: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Head of Product, TechCorp", "max_length": 100},
                    ),
                    63: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 60), ("author", 61), ("role", 62), ("avatar", 22)]],
                        {},
                    ),
                    64: (
                        "wagtail.blocks.ListBlock",
                        (63,),
                        {"max_num": 6, "min_num": 1},
                    ),
                    65: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 58),
                                ("headline", 59),
                                ("testimonials", 64),
                                ("background", 36),
                            ]
                        ],
                        {},
                    ),
                    66: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "How it works",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    67: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Built for creators and teams", "max_length": 200},
                    ),
                    68: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Our platform brings together everything you need to create, collaborate, and publish. From idea to execution, we've got you covered with powerful tools designed for modern teams."
                        },
                    ),
                    69: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    70: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Feature illustration",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    71: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 69), ("alt", 70)]],
                        {"label": "Image"},
                    ),
                    72: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("right", "Right")],
                            "label": "Image position",
                        },
                    ),
                    73: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 13), ("href", 14), ("variant", 15), ("size", 16)]],
                        {"label": "Call to Action", "required": False},
                    ),
                    74: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 66),
                                ("headline", 67),
                                ("description", 68),
                                ("image", 71),
                                ("image_position", 72),
                                ("cta", 73),
                                ("background", 36),
                            ]
                        ],
                        {},
                    ),
                    75: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Trusted by leading companies",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    76: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Partner logo", "max_length": 255},
                    ),
                    77: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "https://example.com",
                            "label": "Link URL",
                            "required": False,
                        },
                    ),
                    78: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 69), ("alt", 76), ("href", 77)]],
                        {},
                    ),
                    79: (
                        "wagtail.blocks.ListBlock",
                        (78,),
                        {"max_num": 12, "min_num": 1},
                    ),
                    80: (
                        "wagtail.blocks.StructBlock",
                        [[("headline", 75), ("logos", 79), ("background", 36)]],
                        {},
                    ),
                    81: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Ready to get started?", "max_length": 200},
                    ),
                    82: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Join thousands of teams already using our platform. Start your free trial today.",
                            "required": False,
                        },
                    ),
                    83: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 13), ("href", 14), ("variant", 15), ("size", 16)]],
                        {"label": "Primary CTA"},
                    ),
                    84: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 13), ("href", 14), ("variant", 15), ("size", 16)]],
                        {"label": "Secondary CTA", "required": False},
                    ),
                    85: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("default", "Default"), ("primary", "Primary")]},
                    ),
                    86: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("headline", 81),
                                ("description", 82),
                                ("primary_cta", 83),
                                ("secondary_cta", 84),
                                ("variant", 85),
                            ]
                        ],
                        {},
                    ),
                    87: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "FAQ", "max_length": 50, "required": False},
                    ),
                    88: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Frequently asked questions", "max_length": 200},
                    ),
                    89: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Everything you need to know about our platform. Can't find the answer you're looking for? Contact our support team.",
                            "required": False,
                        },
                    ),
                    90: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "How does this work?", "max_length": 200},
                    ),
                    91: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Our platform is designed to be intuitive and easy to use. Simply sign up, create your first project, and start collaborating with your team right away."
                        },
                    ),
                    92: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 90), ("answer", 91)]],
                        {},
                    ),
                    93: (
                        "wagtail.blocks.ListBlock",
                        (92,),
                        {"max_num": 20, "min_num": 1},
                    ),
                    94: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 87),
                                ("headline", 88),
                                ("description", 89),
                                ("faqs", 93),
                                ("background", 36),
                            ]
                        ],
                        {},
                    ),
                    95: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "YourBrand",
                            "help_text": "Brand name or tagline",
                            "max_length": 100,
                        },
                    ),
                    96: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Building the future of content management, one block at a time.",
                            "required": False,
                        },
                    ),
                    97: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Company", "max_length": 100},
                    ),
                    98: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "About Us", "max_length": 100},
                    ),
                    99: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 98), ("url", 14)]],
                        {},
                    ),
                    100: ("wagtail.blocks.ListBlock", (99,), {}),
                    101: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 97), ("links", 100)]],
                        {},
                    ),
                    102: ("wagtail.blocks.ListBlock", (101,), {"max_num": 4}),
                    103: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "© 2026 YourBrand. All rights reserved.",
                            "max_length": 200,
                        },
                    ),
                    104: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("brand_text", 95),
                                ("description", 96),
                                ("columns", 102),
                                ("copyright", 103),
                            ]
                        ],
                        {},
                    ),
                    105: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "<p>Add your content here. This section supports rich text formatting including <strong>bold</strong>, <em>italic</em>, links, lists, and more.</p>"
                        },
                    ),
                    106: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Small (640px)"),
                                ("md", "Medium (768px)"),
                                ("lg", "Large (1024px)"),
                            ]
                        },
                    ),
                    107: (
                        "wagtail.blocks.StructBlock",
                        [[("content", 105), ("max_width", 106), ("background", 36)]],
                        {},
                    ),
                },
            ),
        ),
    ]
