# Generated by Django 6.0.3 on 2026-03-24 18:47

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0015_alter_testpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("rich_text", 1),
                    ("hero", 11),
                    ("badge", 14),
                    ("cms_button", 9),
                    ("enhanced_hero", 22),
                    ("feature_grid", 33),
                    ("pricing_section", 46),
                    ("stats_section", 53),
                    ("testimonial_section", 61),
                    ("text_with_image", 70),
                    ("logo_cloud", 76),
                    ("container", 80),
                    ("cta_banner", 85),
                    ("faq_section", 93),
                    ("footer_section", 103),
                    ("rich_text_section", 106),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Welcome to our platform", "max_length": 200},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Discover powerful tools to transform your workflow",
                            "max_length": 400,
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "<p>Start building amazing experiences today with our comprehensive suite of features designed for modern teams.</p>",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Get Started", "max_length": 100},
                    ),
                    6: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"default": "https://example.com"},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("outline", "Outline"),
                                ("ghost", "Ghost"),
                            ]
                        },
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Small"),
                                ("md", "Medium"),
                                ("lg", "Large"),
                            ]
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 5), ("href", 6), ("variant", 7), ("size", 8)]],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.ListBlock",
                        (9,),
                        {"label": "Buttons", "max_num": 2, "min_num": 0},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 2),
                                ("subheading", 3),
                                ("body", 4),
                                ("buttons", 10),
                            ]
                        ],
                        {},
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "New Feature", "max_length": 100},
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default"),
                                ("highlight", "Highlight"),
                                ("muted", "Muted"),
                            ]
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 12), ("variant", 13)]],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Introducing", "max_length": 50, "required": False},
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Build amazing experiences with our platform",
                            "max_length": 200,
                        },
                    ),
                    17: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Powerful tools and features to help you create, manage, and scale your content with ease. Join thousands of teams already using our platform."
                        },
                    ),
                    18: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Hero image", "max_length": 255, "required": False},
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 18), ("alt", 19)]],
                        {"label": "Hero Image", "required": False},
                    ),
                    21: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("left", "Left"), ("center", "Center")]},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 15),
                                ("headline", 16),
                                ("description", 17),
                                ("buttons", 10),
                                ("image", 20),
                                ("alignment", 21),
                            ]
                        ],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Features", "max_length": 50, "required": False},
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Everything you need to succeed",
                            "max_length": 200,
                        },
                    ),
                    25: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Powerful features designed to help you work smarter and faster.",
                            "required": False,
                        },
                    ),
                    26: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("2", "2 columns"),
                                ("3", "3 columns"),
                                ("4", "4 columns"),
                            ]
                        },
                    ),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "⚡",
                            "help_text": "Emoji or icon character (e.g., 🚀, ⚡, 💡)",
                            "max_length": 10,
                        },
                    ),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Lightning Fast", "max_length": 100},
                    ),
                    29: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Built for speed and performance. Experience instant page loads and seamless interactions."
                        },
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 27), ("title", 28), ("description", 29)]],
                        {},
                    ),
                    31: (
                        "wagtail.blocks.ListBlock",
                        (30,),
                        {"max_num": 12, "min_num": 1},
                    ),
                    32: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default"),
                                ("surface", "Surface"),
                                ("secondary", "Secondary"),
                            ]
                        },
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 23),
                                ("headline", 24),
                                ("description", 25),
                                ("columns", 26),
                                ("features", 31),
                                ("background", 32),
                            ]
                        ],
                        {},
                    ),
                    34: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Pricing", "max_length": 50, "required": False},
                    ),
                    35: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Choose your plan", "max_length": 200},
                    ),
                    36: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Simple, transparent pricing that grows with you. Try any plan free for 14 days.",
                            "required": False,
                        },
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Professional", "max_length": 100},
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "$29/mo",
                            "help_text": "e.g., $29/mo",
                            "max_length": 50,
                        },
                    ),
                    39: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"default": "Perfect for growing teams and businesses"},
                    ),
                    40: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Unlimited projects", "max_length": 200},
                    ),
                    41: ("wagtail.blocks.ListBlock", (40,), {"label": "Features"}),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 5), ("href", 6), ("variant", 7), ("size", 8)]],
                        {"label": "Call to Action"},
                    ),
                    43: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Highlight this plan with special styling",
                            "required": False,
                        },
                    ),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 37),
                                ("price", 38),
                                ("description", 39),
                                ("features", 41),
                                ("cta", 42),
                                ("highlighted", 43),
                            ]
                        ],
                        {},
                    ),
                    45: (
                        "wagtail.blocks.ListBlock",
                        (44,),
                        {"max_num": 4, "min_num": 1},
                    ),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 34),
                                ("headline", 35),
                                ("description", 36),
                                ("plans", 45),
                                ("background", 32),
                            ]
                        ],
                        {},
                    ),
                    47: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "By the numbers",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    48: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Trusted by teams worldwide",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    49: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "99.9%",
                            "help_text": "e.g., 99.9%, 10k+, $1M",
                            "max_length": 50,
                        },
                    ),
                    50: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Uptime", "max_length": 100},
                    ),
                    51: (
                        "wagtail.blocks.StructBlock",
                        [[("value", 49), ("label", 50)]],
                        {},
                    ),
                    52: (
                        "wagtail.blocks.ListBlock",
                        (51,),
                        {"max_num": 8, "min_num": 1},
                    ),
                    53: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 47),
                                ("headline", 48),
                                ("stats", 52),
                                ("background", 32),
                            ]
                        ],
                        {},
                    ),
                    54: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Testimonials",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    55: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Loved by teams everywhere", "max_length": 200},
                    ),
                    56: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "This platform has completely transformed how we work. The tools are intuitive and powerful."
                        },
                    ),
                    57: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Sarah Johnson", "max_length": 100},
                    ),
                    58: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Head of Product, TechCorp", "max_length": 100},
                    ),
                    59: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 56), ("author", 57), ("role", 58), ("avatar", 18)]],
                        {},
                    ),
                    60: (
                        "wagtail.blocks.ListBlock",
                        (59,),
                        {"max_num": 6, "min_num": 1},
                    ),
                    61: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 54),
                                ("headline", 55),
                                ("testimonials", 60),
                                ("background", 32),
                            ]
                        ],
                        {},
                    ),
                    62: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "How it works",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    63: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Built for creators and teams", "max_length": 200},
                    ),
                    64: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Our platform brings together everything you need to create, collaborate, and publish. From idea to execution, we've got you covered with powerful tools designed for modern teams."
                        },
                    ),
                    65: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    66: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Feature illustration",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    67: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 65), ("alt", 66)]],
                        {"label": "Image"},
                    ),
                    68: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("right", "Right")],
                            "label": "Image position",
                        },
                    ),
                    69: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 5), ("href", 6), ("variant", 7), ("size", 8)]],
                        {"label": "Call to Action", "required": False},
                    ),
                    70: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 62),
                                ("headline", 63),
                                ("description", 64),
                                ("image", 67),
                                ("image_position", 68),
                                ("cta", 69),
                                ("background", 32),
                            ]
                        ],
                        {},
                    ),
                    71: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Trusted by leading companies",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    72: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Partner logo", "max_length": 255},
                    ),
                    73: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "default": "https://example.com",
                            "label": "Link URL",
                            "required": False,
                        },
                    ),
                    74: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 65), ("alt", 72), ("href", 73)]],
                        {},
                    ),
                    75: (
                        "wagtail.blocks.ListBlock",
                        (74,),
                        {"max_num": 12, "min_num": 1},
                    ),
                    76: (
                        "wagtail.blocks.StructBlock",
                        [[("headline", 71), ("logos", 75), ("background", 32)]],
                        {},
                    ),
                    77: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Reverse order on mobile", "required": False},
                    ),
                    78: ("wagtail.blocks.StreamBlock", [[("logo_cloud", 76)]], {}),
                    79: (
                        "wagtail.blocks.ListBlock",
                        (78,),
                        {"label": "Content", "max_num": 4, "min_num": 1},
                    ),
                    80: (
                        "wagtail.blocks.StructBlock",
                        [[("reverse", 77), ("content", 79)]],
                        {},
                    ),
                    81: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Ready to get started?", "max_length": 200},
                    ),
                    82: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Join thousands of teams already using our platform. Start your free trial today.",
                            "required": False,
                        },
                    ),
                    83: (
                        "wagtail.blocks.ListBlock",
                        (9,),
                        {
                            "help_text": "Add one or more call-to-action buttons",
                            "label": "Buttons",
                            "max_num": 3,
                            "min_num": 0,
                        },
                    ),
                    84: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("default", "Default"), ("primary", "Primary")]},
                    ),
                    85: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("headline", 81),
                                ("description", 82),
                                ("buttons", 83),
                                ("variant", 84),
                            ]
                        ],
                        {},
                    ),
                    86: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "FAQ", "max_length": 50, "required": False},
                    ),
                    87: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Frequently asked questions", "max_length": 200},
                    ),
                    88: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Everything you need to know about our platform. Can't find the answer you're looking for? Contact our support team.",
                            "required": False,
                        },
                    ),
                    89: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "How does this work?", "max_length": 200},
                    ),
                    90: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Our platform is designed to be intuitive and easy to use. Simply sign up, create your first project, and start collaborating with your team right away."
                        },
                    ),
                    91: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 89), ("answer", 90)]],
                        {},
                    ),
                    92: (
                        "wagtail.blocks.ListBlock",
                        (91,),
                        {"max_num": 20, "min_num": 1},
                    ),
                    93: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("badge", 86),
                                ("headline", 87),
                                ("description", 88),
                                ("faqs", 92),
                                ("background", 32),
                            ]
                        ],
                        {},
                    ),
                    94: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "YourBrand",
                            "help_text": "Brand name or tagline",
                            "max_length": 100,
                        },
                    ),
                    95: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "default": "Building the future of content management, one block at a time.",
                            "required": False,
                        },
                    ),
                    96: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Company", "max_length": 100},
                    ),
                    97: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "About Us", "max_length": 100},
                    ),
                    98: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 97), ("url", 6)]],
                        {},
                    ),
                    99: ("wagtail.blocks.ListBlock", (98,), {}),
                    100: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 96), ("links", 99)]],
                        {},
                    ),
                    101: ("wagtail.blocks.ListBlock", (100,), {"max_num": 4}),
                    102: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "© 2026 YourBrand. All rights reserved.",
                            "max_length": 200,
                        },
                    ),
                    103: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("brand_text", 94),
                                ("description", 95),
                                ("columns", 101),
                                ("copyright", 102),
                            ]
                        ],
                        {},
                    ),
                    104: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "<p>Add your content here. This section supports rich text formatting including <strong>bold</strong>, <em>italic</em>, links, lists, and more.</p>"
                        },
                    ),
                    105: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Small (640px)"),
                                ("md", "Medium (768px)"),
                                ("lg", "Large (1024px)"),
                            ]
                        },
                    ),
                    106: (
                        "wagtail.blocks.StructBlock",
                        [[("content", 104), ("max_width", 105), ("background", 32)]],
                        {},
                    ),
                },
            ),
        ),
    ]
